export const ADD_TO_CART = `ADD_TO_CART`
export const CHANGE_COUNTRY = `CHANGE_COUNTRY`
export const CHANGE_API_LANGUAGE = `CHANGE_API_LANGUAGE`
export const COUNTRY_MODAL = `COUNTRY_MODAL`
export const LANGUAGE_MODAL = `LANGUAGE_MODAL`
export const COUNTRY_PAGE_DISABLE = `COUNTRY_PAGE_DISABLE`

export const ALL_PRODUCTS = `ALL_PRODUCTS`
export const CHANGE_PAGElOADER = `CHANGE_PAGElOADER`
export const CHANGE_ENGLISH_CART = `CHANGE_ENGLISH_CART`

export const USER_NAME = `USER_NAME`
export const USER_EMAIL = `USER_EMAIL`
export const USER_ADDRESS = `USER_ADDRESS`
export const USER_CITY = `USER_CITY`
export const USER_PHONE = `USER_PHONE`

export const USER_COUNTRY = `USER_COUNTRY`
export const USER_COUNTRY_CODE = `USER_COUNTRY_CODE`

export const USER_CREDIT_CARD_NUMBER = `USER_CREDIT_CARD_NUMBER`
export const USER_CREDIT_CARD_CVC = `USER_CREDIT_CARD_CVC`
export const USER_CREDIT_CARD_EXPIRY_DATE = `USER_CREDIT_CARD_EXPIRY_DATE`

export const CHANGE_USER_DATA = `CHANGE_USER_DATA`
export const CHANGE_USER_INFORMATION = `CHANGE_USER_INFORMATION`

export const ORDERS_LIST = `ORDERS_LIST`
